### ISSUE TITLE
min VM size and "Waiting for auth-pdp to start"

### ISSUE THREAD

**Issue by TiloGit** [ibm-cloud-architecture/terraform-icp-azure#13]
Hi, quick tip. I try to run with some  `Standard_D2s_v3` to be more cost efficient, but got into trouble as min spec of ICP 3 were not met. 

Maybe add the HW req link to the readme as reference. 
https://www.ibm.com/support/knowledgecenter/en/SSBS6K_3.1.2/supported_system_config/hardware_reqs.html
Error I got: (like this https://www-01.ibm.com/support/docview.wss?uid=ibm10732862)

```
module.icpprovision.null_resource.icp-install (remote-exec): TASK [waitfor : Waiting for auth-pdp to start] *********************************
module.icpprovision.null_resource.icp-install (remote-exec): Monday 25 February 2019  23:06:55 +0000 (0:00:00.086)       0:24:05.442 *******
module.icpprovision.null_resource.icp-install: Still creating... (24m10s elapsed)
module.icpprovision.null_resource.icp-install (remote-exec): FAILED - RETRYING: Waiting for auth-pdp to start (100 retries left).
module.icpprovision.null_resource.icp-install: Still creating... (24m20s elapsed)
module.icpprovision.null_resource.icp-install: Still creating... (24m30s elapsed)
module.icpprovision.null_resource.icp-install: Still creating... (24m40s elapsed)
module.icpprovision.null_resource.icp-install: Still creating... (24m50s elapsed)
```

**Comment by hassenius** [comment]
Thanks, I'll try improve the documentation. Feel free to do a Pull Request if you have suggestions as to where this may be added. Guidance on contributing here: https://github.com/ibm-cloud-architecture/terraform-icp-azure/blob/master/CONTRIBUTING.md

**Comment by hassenius** [comment]
Also worth noting that the auth components can take a very long time to start fully (which is why the retry is set to 100)

**Comment by mastersingh24** [comment]
`FAILED - RETRYING: Waiting for auth-pdp to start (96 retries left).`
