### ISSUE TITLE
How to change AZ sub?

### ISSUE THREAD

**Issue by TiloGit** [ibm-cloud-architecture/terraform-icp-azure#8]
Where/how can we change the subscription to use? 

main.tf? like 

`provider "azurerm" {subscription_id = "zzzz-zzz-zzz-zzz-zzzz" }`

**Comment by hassenius** [comment]
Hi @TiloGit , currently this is handled via az cli. 
So for example as highlighted in https://www.terraform.io/docs/providers/azurerm/auth/azure_cli.html

```
Should you have more than one Subscription, you can specify the Subscription to use via the following command:

$ az account set --subscription="SUBSCRIPTION_ID"
```

I'll try improve documentation a little. Feel free to do a PR if you have ideas of doc or other improvements
