### ISSUE TITLE
How to change default fault domain as per AZ region?

### ISSUE THREAD

**Issue by TiloGit** [ibm-cloud-architecture/terraform-icp-azure#9]
https://www.terraform.io/docs/providers/azurerm/r/availability_set.html#platform_fault_domain_count

in  instances.tf? 
`platform_fault_domain_count`

**Comment by hassenius** [comment]
Yes, that is correct.  Currently the defaults apply (3 for fault domain and 5 for update domains) as defined in terraform provider.
